# Build Stage
FROM microsoft/aspnetcore-build AS build-env
WORKDIR /src

#   Copy only .csproj and restore
COPY ./Fiver.Asp.Docker.Web/Fiver.Asp.Docker.Web.csproj ./Fiver.Asp.Docker.Web/
RUN dotnet restore ./Fiver.Asp.Docker.Web/

#   Copy everything else and build
COPY ./Fiver.Asp.Docker.Web/ ./Fiver.Asp.Docker.Web/
RUN dotnet build ./Fiver.Asp.Docker.Web/

#   publish
RUN dotnet publish ./Fiver.Asp.Docker.Web/ -o /publish --configuration Release

# Publish Stage
FROM microsoft/aspnetcore
ENV Api_Url=
WORKDIR /app
COPY --from=build-env /publish .
ENTRYPOINT ["dotnet", "Fiver.Asp.Docker.Web.dll"]