version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    image: fiver.asp.docker.api
    ports:
      - "8080:80"
    env_file:
      - ./.env
    environment:
      - "ConnectionStrings:DefaultConnection=Server=tcp:fiver.database.windows.net,1433;Initial Catalog=movies;Persist Security Info=False;User ID=${USER_ID};Password=${PASSWORD};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    image: fiver.asp.docker.web
    ports:
      - "8090:80"
    environment:
      - "Api_Url=http://api/movies"
    depends_on:
      - api