# Build Stage
FROM microsoft/aspnetcore-build AS build-env
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet build
RUN dotnet publish ./Fiver.Asp.Docker.Api/ -o /publish --configuration Release

# Publish Stage
FROM microsoft/aspnetcore
WORKDIR /app
COPY --from=build-env /publish .
ENTRYPOINT ["dotnet", "Fiver.Asp.Docker.Api.dll"]