version: '3.3'

services:
  api:
    image: naushadt25/api:ci-4
    # ports:
    #   - "8080:80"
    environment:
      - "ConnectionStrings:DefaultConnection=Server=tcp:fiver.database.windows.net,1433;Initial Catalog=movies;Persist Security Info=False;User ID=fiver;Password=Movies123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  tests:
    build:
      context: .
      dockerfile: Dockerfile_tests
    image: fiver.asp.docker.tests
    environment:
      - "Api_Url=http://api/movies"
    depends_on:
      - api